(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var src_1=require("../../src"),debug=require("debug");debug.enable("example:*");var pbkdf2=src_1.default({iterations:8192,length:32}),rawpbkdf2=src_1.default({encoding:"none",iterations:8192,length:32});debug("example:")("digest passphrase..."),pbkdf2("secret passphrase").then(debug("example:digest:")),rawpbkdf2("secret passphrase").then(debug("example:raw-digest:"));
},{"../../src":2,"debug":undefined}],2:[function(require,module,exports){
(function (Buffer){
"use strict";function getPbkdf2Sha512Spec(t,e){var n=tslib_1.__assign({},e),r=getEncoding(n.encoding),i=getSaltBuffer(t,n.salt,r),f={encoding:r,salt:{bytes:i},iterations:getIterations(n.iterations),length:getLength(n.length)};return"none"!==r&&(f.salt.chars=i.toString(r)),f}function getSaltBuffer(t,e,n){var r=toBufferIfUintArray(toRandomBufferIfNumber(t,toBufferIfString(e,n)));return Buffer.isBuffer(r)&&r.length>=PBKDF2_CONFIG_DEFAULTS.salt.min?Buffer.from(r):t(PBKDF2_CONFIG_DEFAULTS.salt.default)}function toRandomBufferIfNumber(t,e){return utils_1.isNumber(e)?t(e.valueOf()):e}function toBufferIfUintArray(t){try{return t&&utils_1.isArrayBuffer(t.buffer)?Buffer.from(t.buffer):t}catch(e){return t}}function getEncoding(t){var e=utils_1.isString(t)&&t.valueOf();return PBKDF2_CONFIG_DEFAULTS.encoding.indexOf(e)>=0?e:PBKDF2_CONFIG_DEFAULTS.encoding[0]}function getIterations(t){var e=utils_1.isNumber(t)&&t.valueOf();return t>=PBKDF2_CONFIG_DEFAULTS.iterations.min?e:PBKDF2_CONFIG_DEFAULTS.iterations.default}function getLength(t){var e=utils_1.isNumber(t)&&t.valueOf();return t>=PBKDF2_CONFIG_DEFAULTS.length.min&&t<=PBKDF2_CONFIG_DEFAULTS.length.max?e:PBKDF2_CONFIG_DEFAULTS.length.default}function toBufferIfString(t,e){return"none"!==e&&utils_1.isString(t)?Buffer.from(t.valueOf(),e):t}Object.defineProperty(exports,"__esModule",{value:!0});var utils_1=require("./utils"),tslib_1=require("tslib"),PBKDF2_CONFIG_DEFAULTS={encoding:["base64","utf8","latin1","binary","ascii","hex","none"],salt:{default:64,min:32},iterations:{default:65536,min:8192},length:{default:64,min:32,max:64}},Pbkdf2Sha512Class=function(){function t(t,e,n,r,i){this.pbkdf2=t,this.encoding=e,this.salt=n,this.iterations=r,this.length=i,this.hmac="sha512"}return t.prototype.hash=function(t){var e=this,n={encoding:this.encoding,salt:this.salt.chars||this.salt.bytes,iterations:this.iterations,length:this.length,hmac:this.hmac};return new Promise(function(r,i){e.pbkdf2(t,e.salt.bytes,e.iterations,e.length,e.hmac,function(t,f){t&&i(t);var a={value:"none"===e.encoding?f:f.toString(e.encoding),spec:n};r(a)})})},t}();Pbkdf2Sha512Class.getKdf=function(t){var e=t&&t.pbkdf2||require("pbkdf2").pbkdf2,n=t&&t.randombytes||require("randombytes"),r=getPbkdf2Sha512Spec(n,t),i=new Pbkdf2Sha512Class(e,r.encoding,r.salt,r.iterations,r.length);return function(t){var e=toBufferIfUintArray(toBufferIfString(t,"utf8"));return Buffer.isBuffer(e)?i.hash(e):Promise.reject(new TypeError("invalid password"))}};var getPbkdf2Sha512=Pbkdf2Sha512Class.getKdf;exports.default=getPbkdf2Sha512;
}).call(this,require("buffer").Buffer)
},{"./utils":3,"buffer":undefined,"pbkdf2":undefined,"randombytes":undefined,"tslib":undefined}],3:[function(require,module,exports){
"use strict";function isString(r){return"string"==typeof(r&&r.valueOf())}function isNumber(r){return"number"==typeof(r&&r.valueOf())}function isArrayBuffer(r){return"[object ArrayBuffer]"===Object.prototype.toString.call(r)}Object.defineProperty(exports,"__esModule",{value:!0}),exports.isString=isString,exports.isNumber=isNumber,exports.isArrayBuffer=isArrayBuffer;
},{}]},{},[1]);
